### ISSUE TITLE
How to use React-Simple-code-editor with this ? Please help

### ISSUE THREAD

**Issue by pratiksharm** [burhanuday/react-transliterate#12]
Since you have mentioned, that we can use, components .
I tried using but it is giving me length error.
 Please can you guide me how can i use react-simple-code-editor with this... >>>> 👍

**Comment by burhanuday** [comment]
share a codesandbox or github link with what you have tried and i'll see how i can help

**Comment by pratiksharm** [comment]
Thanks for the reply man. You are great!! 
The issue is resolved. As I manually got into the your module code base and added React-simple-code-editor on place of Textarea :) ..
The new code editor will have your module + prismjs. I didn't thought i will be able to make a code-editor with syntax highlight and hindi typing. 
We are trying to make coding in Devanagari. 
You can check us out at [here](http://xn--11by0j.com/). We also have an App in production Bholu.
