### ISSUE TITLE
Position of suggestion box

### ISSUE THREAD

**Issue by dsardar099** [burhanuday/react-transliterate#13]
I am using one textarea and that is scrollable. When I have to scroll the textarea for typing text then that time the position of the suggestion box goes bottom of the whole webpage and that goes down accordingly with respect to the height of the whole textarea and scroll position.
Please solve this issue.

**Comment by burhanuday** [comment]
Hello. Is this happening on all browsers?
If not, give browser information like name and version 
If possible, provide a codesandbox

**Comment by dsardar099** [comment]
Happening on all the browsers.

**Comment by burhanuday** [comment]
https://codesandbox.io/s/epic-lamarr-iwv47?file=/src/App.js

Please try this codesandbox. It seems to be working fine for me. for textarea, use the `Component` prop and set it to `Component="textarea"`. If you still see the bug, share a similar codesandbox for me to reproduce the bug

**Comment by burhanuday** [comment]
I was able to reproduce it. Will look into it. Thank you

**Comment by dsardar099** [comment]
Thanks for your support. Please try to fix it as soon as possible. I am using this package in my current project and this is very much helpful to me.

**Comment by burhanuday** [comment]
please update to version 1.0.4
Its not perfect but i am working on improving the calculation
I am keeping this issue open in case someone comes up with a better solution

**Comment by dsardar099** [comment]
Ok. Thanks.
