### ISSUE TITLE
[feature] api to perform transliteration without using the input

### ISSUE THREAD

**Issue by burhanuday** [burhanuday/react-transliterate#14]
add a function to be able to perform transliteration in case the user does not want to use the component

**Comment by StTronn** [comment]
Hey, this seems like a good issue is this up for contrib. Any ideas on API of the function I guess should be same as the component

**Comment by burhanuday** [comment]
Hi
https://github.com/burhanuday/react-transliterate/blob/4aae9319c2f75c6d241d91006d987dcca7151ecb/src/index.tsx#L101-L125

You can take a look at this code that currently fetches the suggestions from Google Input API. And then export a function from the file that helps fetch the suggestions without breaking the component :smile:

**Comment by StTronn** [comment]
okay will do thanks :)

**Comment by StTronn** [comment]
Sorry for the late pr #27 I have written the function in the same file due to its small size. Let me know if any thing can be improved or is missing :)

**Comment by burhanuday** [comment]
closed by https://github.com/burhanuday/react-transliterate/pull/27
