### ISSUE TITLE
Adding Debouncing to reduce number of API hits

### ISSUE THREAD

**Issue by hardikhere** [burhanuday/react-transliterate#21]
Hey great work I appreciate that,
How About using debouncing in text box, It may optimize our performance and help to reduce number of API hits
I can implement if you assign me.

**Comment by hardikhere** [comment]
We can use lodash/debounce, it sure is great utility

**Comment by burhanuday** [comment]
Hi @hardikhere. That seems like a good idea. I am concerned about how much it would change the user experience if the suggestions aren't being shown as soon as the word changes. Do go on though, i'll assign this issue to you

**Comment by hardikhere** [comment]
UX will not be much affected, one more thing we can do is take a prop from user like useDebounce:true, if its true then only we're gonna use it. what you say?

**Comment by burhanuday** [comment]
Would you like to work on the `debounceFunction` feature?
