### ISSUE TITLE
Mouse click not  working on suggested word drop down. 

### ISSUE THREAD

**Issue by Nphadtare2021** [burhanuday/react-transliterate#31]

**Comment by burhanuday** [comment]
The `onBlur` handler is interfering with the mouse clicks

https://github.com/burhanuday/react-transliterate/blob/f92036d6efa19ffc5620bfa60e2e836fde4b2d49/src/index.tsx#L219-L230

The current implementation takes the first suggestion as the value in case of a blur event. I guess that needs to be disabled or rethought
