### ISSUE TITLE
Suggestions are not proper while clicking backspace

### ISSUE THREAD

**Issue by Santosh-13** [burhanuday/react-transliterate#35]
https://user-images.githubusercontent.com/45909263/136807609-742efff0-98d8-49e6-be04-e396bac918e4.mp4

As shown in the video, when I select a word from the suggestion and try to give backspace suggestions seem to be broken.

**Comment by burhanuday** [comment]
Version 1.1.8 fixes this bug. you can install the latest version and test again. reopen issue if its still broken
