### ISSUE TITLE
The key triggers wont work for mobile

### ISSUE THREAD

**Issue by sparkdevv** [burhanuday/react-transliterate#40]
The space/enter or any key trigger isnt working on mobile browsers
event.keyCode is deprecated, should use event.key

**Comment by burhanuday** [comment]
This is a known issue - https://github.com/burhanuday/react-transliterate/issues/25#issue-893395945

The solution is to not use `keyCode` property and to instead use the `key` property in the code here
https://github.com/burhanuday/react-transliterate/blob/76000dce0c46a24208ee6e67e8e6254ece8a5ffc/src/index.tsx#L202-L204

the `TriggerKeys` constant will also have to be changed accordingly. Can you open a PR that fixes this?

**Comment by sparkdevv** [comment]
Sure, I was also about to say that keyCode is deprecated, and i was trying to fix it but "npm install" fails, some parcel/transformer undefined assertion

**Comment by sparkdevv** [comment]
I can PR without testing tho, few changes i guess

**Comment by burhanuday** [comment]
Fixed in release 1.1.9. please update in package json
